### ISSUE TITLE
python3.6 get UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-14: ordinal not in range(128)

### ISSUE THREAD

**Issue by Yazhou-Liu** [lixiang0/WEB_KG#11]
Traceback (most recent call last):
  File "html_parser.py", line 55, in <module>
    new_urls, _ = parser.parse(content)
  File "html_parser.py", line 44, in parse
    is_saved = self._save_new_data( soup,html_cont)
  File "html_parser.py", line 34, in _save_new_data
    with open(os.path.join(path ,title+'.html'), 'w') as f:
UnicodeEncodeError: 'ascii' codec can't encode characters in position 11-14: ordinal not in range(128)

**Comment by lixiang0** [comment]
这个是Windows编码问题。建议用ubuntu运行。
