### ISSUE TITLE
No such file or directory实在不太清楚缺少了啥

### ISSUE THREAD

**Issue by lpscq** [lixiang0/WEB_KG#26]
D:\bandzip\WEB_KG-master\baike\spiders>python baike.py
Traceback (most recent call last):
  File "baike.py", line 20, in <module>
    class BaikeSpider(scrapy.Spider):
  File "baike.py", line 30, in BaikeSpider
    driver = GraphDatabase.driver(
  File "d:\ProgramData\Anaconda3\lib\site-packages\neo4j\__init__.py", line 120, in driver
    return Driver(uri, **config)
  File "d:\ProgramData\Anaconda3\lib\site-packages\neo4j\__init__.py", line 161, in __new__
    return subclass(uri, **config)
  File "d:\ProgramData\Anaconda3\lib\site-packages\neo4j\__init__.py", line 235, in __new__
    pool.release(pool.acquire())
  File "d:\ProgramData\Anaconda3\lib\site-packages\neobolt\direct.py", line 715, in acquire
    return self.acquire_direct(self.address)
  File "d:\ProgramData\Anaconda3\lib\site-packages\neobolt\direct.py", line 608, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
  File "d:\ProgramData\Anaconda3\lib\site-packages\neo4j\__init__.py", line 232, in connector
    return connect(address, **dict(config, **kwargs))
  File "d:\ProgramData\Anaconda3\lib\site-packages\neobolt\direct.py", line 972, in connect
    raise last_error
  File "d:\ProgramData\Anaconda3\lib\site-packages\neobolt\direct.py", line 963, in connect
    s, der_encoded_server_certificate = _secure(s, host, security_plan.ssl_context, **config)
  File "d:\ProgramData\Anaconda3\lib\site-packages\neobolt\direct.py", line 854, in _secure
    s = ssl_context.wrap_socket(s, server_hostname=host if HAS_SNI and host else None)
  File "d:\ProgramData\Anaconda3\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "d:\ProgramData\Anaconda3\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "d:\ProgramData\Anaconda3\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
FileNotFoundError: [Errno 2] No such file or directory

**Comment by lpscq** [comment]
哎呀我好像知道了我第29行没改

**Comment by lpscq** [comment]
但我改完以后，没有报错，但运行一点结果都没有。直接跳出程序了。
只有这一行：(base) D:\bandzip\WEB_KG-master\baike>d:/ProgramData/Anaconda3/python.exe d:/bandzip/WEB_KG-master/baike/spiders/baike.py
