### ISSUE TITLE
neo4j.exceptions.AuthError: The client is unauthorized due to authentication failure. ubuntu下这是什么原因呢？到了最后一步，谢谢

### ISSUE THREAD

**Issue by dupanfei1** [lixiang0/WEB_KG#5]
Traceback (most recent call last):
  File "/home/lab548/Downloads/nlp/QA/WEB_KG-master/kg/insert_to_neo4j.py", line 13, in <module>
    driver = GraphDatabase.driver("bolt://localhost:7687", auth=("neo4j", "123"))
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 94, in driver
    return Driver(uri, **config)
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/api.py", line 133, in __new__
    return subclass(uri, **config)
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/direct.py", line 73, in __new__
    pool.release(pool.acquire())
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/direct.py", line 44, in acquire
    return self.acquire_direct(self.address)
  File "/usr/local/lib/python3.5/dist-packages/neo4j/bolt/connection.py", line 450, in acquire_direct
    connection = self.connector(address, self.connection_error_handler)
  File "/usr/local/lib/python3.5/dist-packages/neo4j/v1/direct.py", line 70, in connector
    return connect(address, security_plan.ssl_context, error_handler, **config)
  File "/usr/local/lib/python3.5/dist-packages/neo4j/bolt/connection.py", line 704, in connect
    raise last_error
  File "/usr/local/lib/python3.5/dist-packages/neo4j/bolt/connection.py", line 696, in connect
    connection = _handshake(s, resolved_address, der_encoded_server_certificate, error_handler, **config)
  File "/usr/local/lib/python3.5/dist-packages/neo4j/bolt/connection.py", line 668, in _handshake
    connection.init()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/bolt/connection.py", line 207, in init
    self.sync()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/bolt/connection.py", line 380, in sync
    detail_delta, summary_delta = self.fetch()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/bolt/connection.py", line 287, in fetch
    return self._fetch()
  File "/usr/local/lib/python3.5/dist-packages/neo4j/bolt/connection.py", line 327, in _fetch
    response.on_failure(summary_metadata or {})
  File "/usr/local/lib/python3.5/dist-packages/neo4j/bolt/response.py", line 61, in on_failure
    raise AuthError(message)
neo4j.exceptions.AuthError: The client is unauthorized due to authentication failure.

**Comment by lixiang0** [comment]
这个问题是因为neo4j的帐号密码不对导致的。参考[链接](http://blog.rubenxiao.com/posts/install-neo4j.html)

**Comment by dupanfei1** [comment]
好的，谢谢，还有个问题请教，运行python insert_to_neo4j.py怎么在neo4j上看知识图谱呢？我这个triples.txt有１２０多万行。

**Comment by lixiang0** [comment]
1.启动neo4j
2.浏览器打开:http://127.0.0.1:7474,按照提示输入用户名和密码
3.登录成功后，在最上面的输入框输入：```MATCH (n:Node) RETURN n LIMIT 1000```，点击右侧运行按钮即可。
